[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rpg-graph"
version = "0.1.0"
description = "Vivarium - A solo RPG set on the desert moon Saharantis"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain",
    "langchain-fireworks",
    "langchain-openai>=1.1.6",
    "langgraph",
    "python-dotenv",
    "requests>=2.32.5",
]

[tool.hatch.build.targets.wheel]
packages = ["rpg_graph"]

[dependency-groups]
dev = [
    "langgraph-cli[inmem]>=0.4.11",
]
